import Navigation from "./navbar";
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }:any) {
    return (
      <html lang="en">
        <body>
            <Navigation />
            <main>{children}</main>
        </body>
      </html>
    )
  }
