import Navigation from "./navbar";
import type { Metadata } from 'next'
import './globals.css'
import clsx from "clsx";
import { poppins, lato, roboto, higuenSerif, brittanySignature } from "./fonts";
import Footer from "./footer";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
 
export default function RootLayout({ children }:any) {
    return (
      <html lang="en">
        <body className={clsx("pt-20", higuenSerif.variable, poppins.variable, lato.variable, roboto.variable, brittanySignature.variable)}>
            <Navigation />
            
            <main>{children}</main>
            <Footer />
        </body>
      </html>
    )
  }
